name: Create Issues and Labels

on: [push]

jobs:
  create-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create labels
        uses: actions-ecosystem/action-create-labels@v1
        with:
          labels: |
            - name: Status: Healthy
              color: 0e8a16
            - name: Status: Sick
              color: d73a4a
            - name: Status: Hungry
              color: fbca04

      - name: Create issues
        uses: peter-evans/create-issue-from-file@v2
        with:
          title: "Dinosaur health update"
          content-filepath: "./.github/ISSUE_TEMPLATE/health_update.md"
          labels: "Status: Healthy"
